spring.application.name=leave

server.port=8080

spring.main.banner-mode=off

# RDB ? ??? DB ??? ?? ???? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# DB? ???? IP (??)
spring.datasource.url=jdbc:mysql://localhost:3306/db1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
# ?? ???/????
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create-drop